### ISSUE TITLE
Feature Request: Italics Mode?

### ISSUE THREAD

**Issue by carlomunguia** [dustypomerleau/tol#1]
Greetings! I've been using Tol since it was released in 2021, absolutely love it for Elixir, Go & Rust development. 

Any possibility of creating an Italics mode or update current mode to support Italics? 

I find them helpful for function signatures & calls.

Let me know your thoughts or if no italics support was a design choice.

**Comment by dustypomerleau** [comment]
I don't personally use italic fonts for coding, but I'm happy to take a PR for an italic variant. Unfortunately, JSON theme formats don't make it convenient to just add a feature gate, so the usual approach is to copy the entire theme to a new file under `themes/tol-italic.json`, add italics to the desired scopes, and then register it as a new theme with `"label": "Tol (italic)"` in `package.json`. Alternatively, if the number of scopes you want is small, you can just override locally with `"fontStyle": "italic"` in `settings.json` as shown in the `README`.
